
app:
  correo: sergiobernalc@outlook.com
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true  
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: app
    url: jdbc:mariadb://localhost:3306/personas_api
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
