spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: ${port:0}
eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
logging:
  level:
    org:
      hibernate:
        sql: debug
