spring:
  cloud:
    gateway:
      routes:
      - id: config-server
        uri: lb://config-server
        predicates:
          - Path=/config-server/**
        filters:
          - StripPrefix=1     
      - id: service-usuarios
        uri: lb://service-usuarios
        predicates:
          - Path=/api/usuarios/**
        filters:
          - StripPrefix=2
      - id: auth-server
        uri: lb://auth-server
        predicates:
          - Path=/api/security/**
        filters:
          - RemoveResponseHeader=X-Response-Foo
          - StripPrefix=2                
          
server:
  port: ${PORT:8090}

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA_SERVER:http://eureka-server:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

config:
  security:
    oauth:
      jwt: 
        key: algun_codigo_secreto_aeiou
